<?php

$title = 'Artikel entfernen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Willst du wirklich den Artikel 
    <b><?php echo $this->escapeHtml($article->name); ?></b> entfernen?
</p>
<?php
$url = $this->url('article', array('action' => 'delete','id' => $this->id,));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $article->id; ?>" />
    <input type="submit" name="del" value="Ja" />
    <input type="submit" name="del" value="Nein" />
</div>
</form>